In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.metrics import r2_score

def get_month(string):
    return string.split("/")[0]

alc_df = pd.read_csv('alc_dataset.csv', nrows=3000000)
alc_df["Month"] = alc_df["Date"].apply(get_month)
alc_df.drop(columns = ["Year", "Date", "Unnamed: 0"], inplace = True)

In [3]:
grouped_df_bottle = alc_df.drop(columns=['Vendor Name', "Volume Sold (Liters)", "Sale (Dollars)"])
grouped_df_bottle = pd.get_dummies(grouped_df_bottle, columns=['Store Name', "Category Name"]).groupby(['Month', 'County', 'Population']).sum().reset_index()

#grouped_df = alc_df.groupby(['Month', 'County', 'Population']).sum().reset_index()

grouped_df_bottle.drop(columns=['County', 'Month'], inplace=True)
#grouped_df = pd.get_dummies(grouped_df, columns=['Month'])
grouped_df_bottle

,Population,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Store Name_218 Fuel Express & Chubby's Liquor,Store Name_3rd St Convenience,Store Name_6 Corners Gas & Grub,Store Name_A J'S LIQUOR II,Store Name_A To Z Liquor and Smoke Shop,...,Category Name_Tennessee Whiskies,Category Name_Triple Sec,Category Name_VODKA 80 PROOF,Category Name_VODKA FLAVORED,Category Name_WATERMELON SCHNAPPS,Category Name_WHISKEY LIQUEUR,Category Name_WHITE CREME DE CACAO,Category Name_WHITE CREME DE MENTHE,Category Name_Whiskey Liqueur,Category Name_White Rum
0,7074,124825.0,1213.33,1820.26,1026.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,3.0
1,7387,272925.0,2322.59,3487.81,2316.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,4.0,0.0,8.0,0.0,0.0,0.0,0.0
2,7468,309625.0,2476.33,3721.56,2219.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,8.0,0.0,10.0,0.0,0.0,0.0,0.0
3,3644,3500.0,21.70,32.55,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3754,90075.0,866.52,1300.94,484.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,4.0,0.0,7.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,37069,2401550.0,25417.21,38220.96,25209.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,328.0,109.0,5.0,100.0,1.0,1.0,0.0,0.0
1714,10430,759575.0,7281.38,10963.80,5138.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,15.0,1.0,27.0,2.0,0.0,0.0,0.0
1715,102284,5778550.0,63178.49,95031.68,66316.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,663.0,296.0,15.0,225.0,4.0,3.0,0.0,0.0
1716,102321,5297225.0,56387.49,84921.64,68284.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,612.0,287.0,6.0,131.0,6.0,2.0,0.0,0.0
1717,7557,334300.0,3281.56,4933.01,1997.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,19.0,0.0,11.0,0.0,0.0,0.0,0.0

In [5]:
def coef_mat(X, Y):
    xtx = np.linalg.inv(np.matmul(X.T, X))
    print(np.matmul(X.T, X).shape)
    print(np.matmul(X.T, X))
    beta_hat = xtx * (X.transpose() * Y.transpose())
    print(beta_hat)
    return beta_hat

def ridge_betas(X, Y, L):
    xtx = np.linalg.inv(X.T.dot(X) + np.identity(X.shape[1])*L)
    beta_hat = xtx.dot(X.T.dot(Y))
    return beta_hat

def ols_regression(X, Y):
    beta_hat = coef_mat(X, Y)
    return X * beta_hat

def ridge_regression(X, Y, L, beta_hat):
    return X.dot(beta_hat)

def lse(Y, y_hat):
    return (Y - y_hat).T.dot(Y - y_hat)

def rss(Y, y_hat):
    return str(np.sum(
        np.square(Y - y_hat)
    ))

def average_pct_err(Y, y_hat):
    return np.mean((abs(Y-y_hat))/abs(Y))

In [7]:
#grouped_df['State Profit per capita'] = (grouped_df['State Bottle Retail'] - grouped_df['State Bottle Cost'])/grouped_df['Population']
#grouped_df['Liters Sold per capita'] = grouped_df['Volume Sold (Liters)'] / grouped_df['Population']
#grouped_df['Sales per capita (Dollars)'] = grouped_df['Sale (Dollars)'] / grouped_df['Population']
grouped_df_bottle['Bottles Sold per capita'] = grouped_df_bottle['Bottles Sold'] / grouped_df_bottle['Population']
# grouped_df.drop(columns=['State Bottle Retail', 'Volume Sold (Liters)', 'Sale (Dollars)', 'Bottles Sold', 'Bottle Volume (ml)', 'State Bottle Cost', 'State Bottle Retail'], inplace=True)
grouped_df_bottle

,Population,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Store Name_218 Fuel Express & Chubby's Liquor,Store Name_3rd St Convenience,Store Name_6 Corners Gas & Grub,Store Name_A J'S LIQUOR II,Store Name_A To Z Liquor and Smoke Shop,...,Category Name_Triple Sec,Category Name_VODKA 80 PROOF,Category Name_VODKA FLAVORED,Category Name_WATERMELON SCHNAPPS,Category Name_WHISKEY LIQUEUR,Category Name_WHITE CREME DE CACAO,Category Name_WHITE CREME DE MENTHE,Category Name_Whiskey Liqueur,Category Name_White Rum,Bottles Sold per capita
0,7074,124825.0,1213.33,1820.26,1026.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,3.0,0.145038
1,7387,272925.0,2322.59,3487.81,2316.0,0.0,0.0,0.0,0.0,0.0,...,0.0,42.0,4.0,0.0,8.0,0.0,0.0,0.0,0.0,0.313524
2,7468,309625.0,2476.33,3721.56,2219.0,0.0,0.0,0.0,0.0,0.0,...,0.0,39.0,8.0,0.0,10.0,0.0,0.0,0.0,0.0,0.297134
3,3644,3500.0,21.70,32.55,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002195
4,3754,90075.0,866.52,1300.94,484.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,4.0,0.0,7.0,1.0,1.0,0.0,0.0,0.128929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,37069,2401550.0,25417.21,38220.96,25209.0,0.0,0.0,0.0,0.0,0.0,...,0.0,328.0,109.0,5.0,100.0,1.0,1.0,0.0,0.0,0.680056
1714,10430,759575.0,7281.38,10963.80,5138.0,0.0,0.0,0.0,0.0,0.0,...,0.0,77.0,15.0,1.0,27.0,2.0,0.0,0.0,0.0,0.492617
1715,102284,5778550.0,63178.49,95031.68,66316.0,0.0,0.0,0.0,0.0,0.0,...,0.0,663.0,296.0,15.0,225.0,4.0,3.0,0.0,0.0,0.648352
1716,102321,5297225.0,56387.49,84921.64,68284.0,0.0,0.0,0.0,0.0,0.0,...,0.0,612.0,287.0,6.0,131.0,6.0,2.0,0.0,0.0,0.667351
1717,7557,334300.0,3281.56,4933.01,1997.0,0.0,0.0,0.0,0.0,0.0,...,0.0,42.0,19.0,0.0,11.0,0.0,0.0,0.0,0.0,0.264258

In [25]:
# Bottles Sold per capita
Y = grouped_df_bottle['Bottles Sold per capita']

bottles_sold_df = grouped_df_bottle.drop(columns=['Bottles Sold per capita',  'Bottles Sold'])
normalize = ['Population', "Bottle Volume (ml)", "State Bottle Cost", "State Bottle Retail"]
bottles_sold_df[normalize] = StandardScaler().fit_transform(bottles_sold_df[normalize])
X_train, X_test, y_train, y_test = train_test_split(bottles_sold_df, Y, test_size=0.2, random_state = 42)


# Training Set
L = 10000
betas1 = ridge_betas(X_train, y_train, L)

y_hat = ridge_regression(X_train, y_train, L, betas1)
err = average_pct_err(y_train, y_hat)
print("TRAINING ERROR: ", err)

# Testing Set
#L = 2000
y_hat = ridge_regression(X_test, y_test, L, betas1)
err = average_pct_err(y_test, y_hat)

print("TESTING ERROR: ", err)
print("R2 Score:", r2_score(y_test, y_hat))

TRAINING ERROR:  0.09520297311037382
TESTING ERROR:  0.12318239369030258
R2 Score: 0.8215294660766482

In [10]:
bottles_sold_df

,Population,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Store Name_218 Fuel Express & Chubby's Liquor,Store Name_3rd St Convenience,Store Name_6 Corners Gas & Grub,Store Name_A J'S LIQUOR II,Store Name_A To Z Liquor and Smoke Shop,Store Name_A-TOWN LIQUOR STORE,...,Category Name_Tennessee Whiskies,Category Name_Triple Sec,Category Name_VODKA 80 PROOF,Category Name_VODKA FLAVORED,Category Name_WATERMELON SCHNAPPS,Category Name_WHISKEY LIQUEUR,Category Name_WHITE CREME DE CACAO,Category Name_WHITE CREME DE MENTHE,Category Name_Whiskey Liqueur,Category Name_White Rum
0,-0.444673,124825.0,1213.33,1820.26,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,3.0
1,-0.439685,272925.0,2322.59,3487.81,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,4.0,0.0,8.0,0.0,0.0,0.0,0.0
2,-0.438394,309625.0,2476.33,3721.56,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,8.0,0.0,10.0,0.0,0.0,0.0,0.0
3,-0.499334,3500.0,21.70,32.55,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.497581,90075.0,866.52,1300.94,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,4.0,0.0,7.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,0.033337,2401550.0,25417.21,38220.96,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,328.0,109.0,5.0,100.0,1.0,1.0,0.0,0.0
1714,-0.391191,759575.0,7281.38,10963.80,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,15.0,1.0,27.0,2.0,0.0,0.0,0.0
1715,1.072623,5778550.0,63178.49,95031.68,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,663.0,296.0,15.0,225.0,4.0,3.0,0.0,0.0
1716,1.073213,5297225.0,56387.49,84921.64,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,612.0,287.0,6.0,131.0,6.0,2.0,0.0,0.0
1717,-0.436976,334300.0,3281.56,4933.01,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,19.0,0.0,11.0,0.0,0.0,0.0,0.0

In [14]:
# Sales volume per capita
grouped_df_sales = alc_df.drop(columns=["Bottles Sold", "State Bottle Retail", "Volume Sold (Liters)", "Vendor Name"])
grouped_df_sales = pd.get_dummies(grouped_df_sales, columns=['Store Name', "Category Name"]).groupby(['Month', 'County', 'Population']).sum().reset_index()
grouped_df_sales.drop(columns=['County'], inplace=True)
grouped_df_sales = pd.get_dummies(grouped_df_sales, columns = ["Month"])
grouped_df_sales

,Population,Bottle Volume (ml),State Bottle Cost,Sale (Dollars),Store Name_218 Fuel Express & Chubby's Liquor,Store Name_3rd St Convenience,Store Name_6 Corners Gas & Grub,Store Name_A J'S LIQUOR II,Store Name_A To Z Liquor and Smoke Shop,Store Name_A-TOWN LIQUOR STORE,...,Month_03,Month_04,Month_05,Month_06,Month_07,Month_08,Month_09,Month_10,Month_11,Month_12
0,7074,124825.0,1213.33,12587.89,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,7387,272925.0,2322.59,27235.71,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,7468,309625.0,2476.33,24355.93,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,3644,3500.0,21.70,107.32,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,3754,90075.0,866.52,4903.92,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,37069,2401550.0,25417.21,328422.61,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1714,10430,759575.0,7281.38,67792.33,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1715,102284,5778550.0,63178.49,864005.66,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1716,102321,5297225.0,56387.49,905288.89,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1717,7557,334300.0,3281.56,27022.17,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [20]:
Y = grouped_df_sales['Sale (Dollars)'] / grouped_df_sales['Population']

sales_df = grouped_df_sales.drop(columns=['Sale (Dollars)'])
normalize = ['Population', "Bottle Volume (ml)", "State Bottle Cost"]
sales_df[normalize] = StandardScaler().fit_transform(sales_df[normalize])
X_train, X_test, y_train, y_test = train_test_split(sales_df, Y, test_size=0.2, random_state = 42)


# Training Set
L = 1000
betas1 = ridge_betas(X_train, y_train, L)

y_hat = ridge_regression(X_train, y_train, L, betas1)
err = average_pct_err(y_train, y_hat)
print("TRAINING ERROR: ", err)

# Testing Set
#L = 2000
y_hat = ridge_regression(X_test, y_test, L, betas1)
err = average_pct_err(y_test, y_hat)


print("TESTING ERROR: ", err)
print("Rscore:", r2_score(y_test, y_hat))

TRAINING ERROR:  0.09140130022588462
TESTING ERROR:  0.14706814999646922
Rscore: 0.7440746737369297

In [16]:
#State Profit per capita
grouped_profit_df = alc_df.drop(columns = ["Vendor Name", "Bottles Sold", "Sale (Dollars)", "Volume Sold (Liters)"])
grouped_profit_df = pd.get_dummies(grouped_profit_df, columns = ["Category Name", "Store Name"]).groupby(['Month', 'County', 'Population']).sum().reset_index().drop(columns=["Month", "County"])
grouped_profit_df

,Population,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Category Name_100 PROOF VODKA,Category Name_100% Agave Tequila,Category Name_AMARETTO - IMPORTED,Category Name_AMERICAN ALCOHOL,Category Name_AMERICAN AMARETTO,Category Name_AMERICAN COCKTAILS,...,Store Name_Wilton Express,Store Name_Wine and Spirits Shoppe Of,Store Name_Wines and Spirits,Store Name_Wj's Liquor,Store Name_World Liquor & Tobacco,Store Name_World Liquor & Tobacco + Vape,Store Name_Xo Food And Liquor,Store Name_Yesway,Store Name_Yesway Store,Store Name_Zapf's Pronto Market
0,7074,124825.0,1213.33,1820.26,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7387,272925.0,2322.59,3487.81,3.0,0.0,0.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7468,309625.0,2476.33,3721.56,4.0,0.0,0.0,1.0,2.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3644,3500.0,21.70,32.55,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3754,90075.0,866.52,1300.94,1.0,0.0,0.0,1.0,2.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,37069,2401550.0,25417.21,38220.96,8.0,0.0,0.0,9.0,12.0,67.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1714,10430,759575.0,7281.38,10963.80,9.0,0.0,0.0,4.0,4.0,10.0,...,0.0,0.0,0.0,142.0,0.0,0.0,0.0,0.0,0.0,0.0
1715,102284,5778550.0,63178.49,95031.68,70.0,0.0,0.0,21.0,29.0,163.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1716,102321,5297225.0,56387.49,84921.64,55.0,0.0,0.0,18.0,35.0,200.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1717,7557,334300.0,3281.56,4933.01,6.0,0.0,0.0,1.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
Y = (grouped_profit_df['State Bottle Retail'] - grouped_profit_df['State Bottle Cost'])/grouped_profit_df['Population']

profit_df = grouped_profit_df.drop(columns=['State Bottle Retail', 'State Bottle Cost'])
normalize = ['Population', "Bottle Volume (ml)"]
profit_df[normalize] = StandardScaler().fit_transform(profit_df[normalize])
X_train, X_test, y_train, y_test = train_test_split(profit_df, Y, test_size=0.2, random_state = 42)


# Training Set
L = 10000
betas1 = ridge_betas(X_train, y_train, L)

y_hat = ridge_regression(X_train, y_train, L, betas1)
err = average_pct_err(y_train, y_hat)
print("TRAINING ERROR: ", err)

# Testing Set
#L = 2000
y_hat = ridge_regression(X_test, y_test, L, betas1)
err = average_pct_err(y_test, y_hat)

print("TESTING ERROR: ", err)
print("Rscore", r2_score(y_hat, y_test))

TRAINING ERROR:  0.07257869041136887
TESTING ERROR:  0.10271861085936605
Rscore 0.8377205586332985

In [19]:
grouped_volume_df = alc_df.drop(columns = ["Vendor Name", "Bottles Sold", "Sale (Dollars)", 'Bottle Volume (ml)'])
grouped_volume_df = pd.get_dummies(grouped_volume_df, columns = ["Category Name", "Store Name"]).groupby(['Month', 'County', 'Population']).sum().reset_index().drop(columns=["Month", "County"])
grouped_volume_df

,Population,State Bottle Cost,State Bottle Retail,Volume Sold (Liters),Category Name_100 PROOF VODKA,Category Name_100% Agave Tequila,Category Name_AMARETTO - IMPORTED,Category Name_AMERICAN ALCOHOL,Category Name_AMERICAN AMARETTO,Category Name_AMERICAN COCKTAILS,...,Store Name_Wilton Express,Store Name_Wine and Spirits Shoppe Of,Store Name_Wines and Spirits,Store Name_Wj's Liquor,Store Name_World Liquor & Tobacco,Store Name_World Liquor & Tobacco + Vape,Store Name_Xo Food And Liquor,Store Name_Yesway,Store Name_Yesway Store,Store Name_Zapf's Pronto Market
0,7074,1213.33,1820.26,951.40,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7387,2322.59,3487.81,2206.62,3.0,0.0,0.0,1.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7468,2476.33,3721.56,2108.94,4.0,0.0,0.0,1.0,2.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3644,21.70,32.55,14.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3754,866.52,1300.94,387.08,1.0,0.0,0.0,1.0,2.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,37069,25417.21,38220.96,22498.96,8.0,0.0,0.0,9.0,12.0,67.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1714,10430,7281.38,10963.80,5369.12,9.0,0.0,0.0,4.0,4.0,10.0,...,0.0,0.0,0.0,142.0,0.0,0.0,0.0,0.0,0.0,0.0
1715,102284,63178.49,95031.68,57901.56,70.0,0.0,0.0,21.0,29.0,163.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1716,102321,56387.49,84921.64,61588.14,55.0,0.0,0.0,18.0,35.0,200.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1717,7557,3281.56,4933.01,2106.17,6.0,0.0,0.0,1.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
Y = (grouped_volume_df['Volume Sold (Liters)']/grouped_volume_df['Population'])

volume_df = grouped_volume_df.drop(columns=['Volume Sold (Liters)'])
normalize = ['Population', "State Bottle Cost", "State Bottle Retail"]
profit_df[normalize] = StandardScaler().fit_transform(volume_df[normalize])
X_train, X_test, y_train, y_test = train_test_split(volume_df, Y, test_size=0.2, random_state = 42)


# Training Set
L = 10000
betas1 = ridge_betas(X_train, y_train, L)

y_hat = ridge_regression(X_train, y_train, L, betas1)
err = average_pct_err(y_train, y_hat)
print("TRAINING ERROR: ", err)

# Testing Set
#L = 2000
y_hat = ridge_regression(X_test, y_test, L, betas1)
err = average_pct_err(y_test, y_hat)

print("TESTING ERROR: ", err)
print("Rscore", r2_score(y_hat, y_test))

TRAINING ERROR:  0.10666193263113077
TESTING ERROR:  0.14277719429517166
Rscore 0.8226628964892908